package aws

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/cloudformation"
)

type cloudformationClient interface {
	CreateStack(*cloudformation.CreateStackInput) (*cloudformation.CreateStackOutput, error)
	DeleteStack(*cloudformation.DeleteStackInput) (*cloudformation.DeleteStackOutput, error)
	DescribeStacks(*cloudformation.DescribeStacksInput) (*cloudformation.DescribeStacksOutput, error)
}

func (c *Client) CreateStack(name string, template string, parameters map[string]string) (string, error) {
	paramSlice := []*cloudformation.Parameter{}
	for k, v := range parameters {
		paramSlice = append(paramSlice, &cloudformation.Parameter{
			ParameterKey:   aws.String(k),
			ParameterValue: aws.String(v),
		})
	}

	out, err := c.Cloudformation.CreateStack(&cloudformation.CreateStackInput{
		StackName:  aws.String(name),
		Parameters: paramSlice,
		Tags: []*cloudformation.Tag{
			&cloudformation.Tag{
				Key:   aws.String("Name"),
				Value: aws.String(name),
			},
			&cloudformation.Tag{
				Key:   aws.String("BOSH_Classroom"),
				Value: aws.String("Autogenerated by proctor tool"),
			},
		},
		TemplateBody: aws.String(template),
	})
	if err != nil {
		return "", err
	}
	return *out.StackId, nil
}

func (c *Client) DeleteStack(nameOrID string) error {
	_, err := c.Cloudformation.DeleteStack(&cloudformation.DeleteStackInput{
		StackName: aws.String(nameOrID),
	})
	return err
}

func (c *Client) DescribeStack(nameOrID string) (string, map[string]string, error) {

	out, err := c.Cloudformation.DescribeStacks(&cloudformation.DescribeStacksInput{
		StackName: aws.String(nameOrID),
	})
	if err != nil {
		return "", nil, err
	}

	parameters := map[string]string{}
	for _, parameter := range out.Stacks[0].Parameters {
		parameters[*parameter.ParameterKey] = *parameter.ParameterValue
	}

	status := *out.Stacks[0].StackStatus

	return status, parameters, nil
}
